### ISSUE TITLE
Formula Doesn't Install Slurm

### ISSUE THREAD

**Issue by jordangumm** [mmarcrr/saltstack-forumula-slurm#1]
I'm a little embarrassed to enquire through an issue, but I cannot for the life of me figure out how to get the required packages installed and recognized.  I can install slurm, but a slurm package doesn't exist if I do this, only the commands like srun, scontrol, etc.
## As an example:

```
      ID: slurm_enable
Function: service.running
    Name: slurm
  Result: False
 Comment: The following requisites were not found:
                             require:
                                 service: munge
 Started: 
Duration: 
 Changes:   
```

---

"Each Salt Formula is an individual Git repository designed as a drop-in addition to an existing Salt State tree."  However, it is unclear (to me) how this formula is a drop-in for installing and configuring a slurm cluster.  Are we required to install munge (among other dependencies) via rpm in a local yum repo for these requirements to be recognized?
